openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /vector-topk:
    get:
      tags:
      - Data Enrichment
      summary: Get top K vector documents and add information to query
      operationId: getTopK
      parameters:
      - name: q
        in: query
        required: false
        schema:
          type: string
          default: recipe for carbonara pasta
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /vector-query:
    get:
      tags:
      - Data Enrichment
      summary: Get a RAG chat response with vector documents
      operationId: ragQuery
      parameters:
      - name: q
        in: query
        required: false
        schema:
          type: string
          default: what is carbonara
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /vector-pdf:
    get:
      tags:
      - Data Enrichment
      summary: Process PDF and add to vector store
      operationId: processPDF
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /vector-init:
    get:
      tags:
      - Data Enrichment
      summary: Initialize vector store with sample documents
      operationId: initVector
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /vector-embed:
    get:
      tags:
      - Data Enrichment
      summary: Embed text to vector
      operationId: embedText
      parameters:
      - name: text
        in: query
        required: false
        schema:
          type: string
          default: Pasta carbonara
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /tool-chat:
    get:
      tags:
      - Text
      summary: Get a chat response with tools for weather and user preferences
      operationId: recipeWeather
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /text-image:
    get:
      tags:
      - Images
      summary: Generate an image from a text prompt
      operationId: recipeImage
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /text-audio:
    get:
      tags:
      - Audio
      summary: Get audio response from text input
      operationId: getAudio
      parameters:
      - name: q
        in: query
        required: false
        schema:
          type: string
          default: What is pasta carbonara
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /system-chat:
    get:
      tags:
      - Text
      summary: Get a chat response with system instructions
      operationId: recipe
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /structure-chat:
    get:
      tags:
      - Text
      summary: Get a chat response with a structured recipe
      operationId: recipeJson
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Recipe"
  /streaming-chat:
    get:
      tags:
      - Text
      summary: Get a streaming chat response with a recipe
      operationId: recipeStream
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /memory-chat:
    get:
      tags:
      - Text
      summary: Get a chat response with memory for the last recipe
      operationId: recipeLast
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /image-text:
    get:
      tags:
      - Images
      summary: Describe a dish from an image
      operationId: recipeImageDescribe
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /fact-check:
    get:
      tags:
      - Testing & Evaluation
      summary: Get a recipe along with its fact-check evaluation
      operationId: recipeFactCheck
      parameters:
      - name: question
        in: query
        required: false
        schema:
          type: string
          default: What is the main ingredient in carbonara?
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FactCheckEvaluation"
  /evaluation:
    get:
      tags:
      - Testing & Evaluation
      summary: Get a recipe along with its relevancy evaluation
      operationId: recipeWithEvaluation
      parameters:
      - name: dish
        in: query
        required: false
        schema:
          type: string
          default: a delicious dish
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecipeEvaluation"
  /blocking-chat:
    get:
      tags:
      - Text
      summary: Get a blocking chat response with a recipe
      operationId: recipe_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /audio-text:
    get:
      tags:
      - Audio
      summary: Transcribe audio to text using GPT-4o Audio
      operationId: getAudioText
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Recipe:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        ingredients:
          type: array
          items:
            type: string
        instructions:
          type: string
    FactCheckEvaluation:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        factualAccuracyScore:
          type: number
          format: double
        isFactuallyCorrect:
          type: boolean
    RecipeEvaluation:
      type: object
      properties:
        dishRequested:
          type: string
        recipe:
          type: string
        relevancyScore:
          type: number
          format: double
        isRelevant:
          type: boolean
